name: Lighthouse
on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://rjmccallumbigl.github.io/'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts        
